/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monalisa.addons.netproperties;

import java.awt.Dimension;
import monalisa.resources.ResourceManager;
import monalisa.resources.StringResources;
import static monalisa.addons.netproperties.AlgorithmInterpretations.HELP;
import monalisa.util.MonaLisaHyperlinkListener;

/**
 *
 * @author jens
 */
public class HelpDialog extends javax.swing.JFrame {

    private static final ResourceManager resources = ResourceManager.instance();
    private static final StringResources strings = resources.getDefaultStrings();    
    
    private final StringBuilder helpText;    
    
    /**
     * Creates new form HelpDialog
     */
    public HelpDialog() {
        setPreferredSize(new Dimension(400,500));
        setSize(new Dimension(400,500));
        setTitle("NetProperties - Help");
        setIconImage(resources.getImage("icon-16.png"));
        
        helpText = new StringBuilder();
        
        helpText.append("<html>");
        
        helpText.append(HELP.get("ordinary"));
        
        helpText.append(HELP.get("homogenous"));
        
        helpText.append(HELP.get("non-blocking multiplicity")); 
        
        helpText.append(HELP.get("pure"));           
                   
        helpText.append(HELP.get("conservative")); 
        
        helpText.append(HELP.get("subConservative"));
        
        helpText.append(HELP.get("staticConflictFree"));
        
        helpText.append(HELP.get("connected"));

        helpText.append(HELP.get("stronglyConnected"));
        
        helpText.append(HELP.get("sources"));
        
        helpText.append("</html>");

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        helpPane = new javax.swing.JEditorPane("text/html", helpText.toString());
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        helpPane.setEditable(false);
        helpPane.setBackground(java.awt.Color.lightGray.brighter());
        helpPane.addHyperlinkListener(new MonaLisaHyperlinkListener());
        jScrollPane1.setViewportView(helpPane);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jScrollPane1, gridBagConstraints);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(closeButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JEditorPane helpPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
