package monalisa.addons.reachability;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.xml.stream.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.io.*;
import java.util.HashMap;
import java.util.Map;
import monalisa.data.pn.PetriNetFacade;
import monalisa.data.pn.Place;
import monalisa.data.pn.Transition;
import java.util.Collection;
import java.util.prefs.Preferences;

/**
 *
 * @author Bo
 */
public class SPNSettingFrame extends javax.swing.JFrame {

    private final ReachabilityDialog rd;
    private HashMap<Transition, Double> firingRates;
    private HashMap<Place, Long> capacities;
    private HashMap<Place, Long> targets;
    private final PetriNetFacade pnf;
   
    
    /**
     * Creates new form FiringrateFrame
     */
    public SPNSettingFrame(ReachabilityDialog rd, PetriNetFacade pnf) //Collection<Transition> transitions
    {
        initComponents();
        DefaultTableModel firingmodel = (DefaultTableModel) firingrateTable.getModel();
        DefaultTableModel captarModel = (DefaultTableModel) captarTable.getModel();

        this.rd = rd;
        this.firingRates = new HashMap<>();
        this.capacities = new HashMap<>();
        this.targets = new HashMap<>();
        this.pnf = pnf;

        for (Transition t : pnf.transitions()) {
            double defaultFiringRate = 0.0;
            firingmodel.addRow(new Object[]{
                t,
                defaultFiringRate
            });
            firingRates.put(t, defaultFiringRate);
        }

        for (Place p : pnf.places()) {
            long defaultCapTar = 0L;  // 默认容量为 0
            captarModel.addRow(new Object[]{
                p, 
                defaultCapTar,
                defaultCapTar});
            capacities.put(p, defaultCapTar);
            targets.put(p, defaultCapTar);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firingrateLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        firingrateTable = new javax.swing.JTable();
        importButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        captarTable = new javax.swing.JTable();
        capacityLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        firingrateLabel.setText("Firing rates");

        firingrateTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Transition", "Firing rate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(firingrateTable);

        importButton.setText("import");
        importButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importButtonActionPerformed(evt);
            }
        });

        saveButton.setText("save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        captarTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Place", "Capacity", "Target"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Long.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(captarTable);

        capacityLabel.setText("Capacities / Targets");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(importButton)
                            .addGap(206, 206, 206)
                            .addComponent(saveButton))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(firingrateLabel)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(capacityLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(firingrateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(capacityLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(importButton)
                    .addComponent(saveButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void importButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importButtonActionPerformed
        Preferences prefs = Preferences.userRoot().node(getClass().getName());
        String lastDir = prefs.get("lastXmlDir", null);  // 读取上次路径
        
        JFileChooser fc = new JFileChooser();
        if (lastDir != null) {
            fc.setCurrentDirectory(new File(lastDir));  // 设置默认目录
        }
        if (fc.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) return;
        File inFile = fc.getSelectedFile();
        prefs.put("lastXmlDir", inFile.getParent());  // 保存新的路径
    
        try {
            XMLInputFactory factory = XMLInputFactory.newInstance();
            XMLStreamReader parser = factory.createXMLStreamReader(new FileInputStream(inFile));
    
            Map<String, Double> nameToRate = new HashMap<>();
            Map<String, Long> nameToCapacity = new HashMap<>();
            Map<String, Long> nametoTarget = new HashMap<>();
 
            while (parser.hasNext()) {
                //  = parser.next();
                int event = parser.getEventType();

                if (event == XMLStreamConstants.START_ELEMENT) {
                    String localName = parser.getLocalName();
                    if ("transition".equals(localName)) {
                        String name = null;
                        double firingRate = 0;
        
                        for (int i = 0; i < parser.getAttributeCount(); i++) {
                            switch (parser.getAttributeLocalName(i)) {
                                case "name":
                                    name = parser.getAttributeValue(i);
                                    break;
                                case "firingRate":
                                    firingRate = Double.parseDouble(parser.getAttributeValue(i));
                                    break;
                            }
                        }
        
                        if (name != null) {
                            nameToRate.put(name, firingRate);
                        }
                    } else if ("capacity".equals(localName)) {
                        String placename = null;
                        long capacity = 0L;

                        for (int i = 0; i < parser.getAttributeCount(); i++) {
                            switch (parser.getAttributeLocalName(i)) {
                                case "name":
                                    placename = parser.getAttributeValue(i);
                                    break;
                                case "cap":
                                    capacity = Long.parseLong(parser.getAttributeValue(i));
                                    break;
                            }
                        }
                        if (placename != null) {
                            nameToCapacity.put(placename, capacity);
                        }
                    }else if("target".equals(localName)){
                        String placename = null;
                        long target = 0L;

                        for (int i = 0; i < parser.getAttributeCount(); i++) {
                            switch (parser.getAttributeLocalName(i)) {
                                case "name":
                                    placename = parser.getAttributeValue(i);
                                    break;
                                case "nrOfTokens":
                                    target = Long.parseLong(parser.getAttributeValue(i));
                                    break;
                            }
                        }
                        if (placename != null) {
                            nametoTarget.put(placename, target);
                        }
                    }
                }
                
                parser.next();
            }
    
            parser.close();
    
            // 更新 firingRates 中的值
            for (Transition t : firingRates.keySet()) {
                String name = (String) t.toString();
                if (nameToRate.containsKey(name)) {
                    firingRates.put(t, nameToRate.get(name));
                }
            }
    
            // 更新 capacities
             for (Place p : capacities.keySet()) {
                String name = (String) p.toString();
                if (nameToCapacity.containsKey(name)) {
                    capacities.put(p, nameToCapacity.get(name));
                }
            }

            // 更新 targets
             for (Place p : targets.keySet()) {
                String name = (String) p.toString();
                if (nametoTarget.containsKey(name)) {
                    targets.put(p, nametoTarget.get(name));
                }
            }

            // 刷新表格内容
            DefaultTableModel firingmodel = (DefaultTableModel) firingrateTable.getModel();
            firingmodel.setRowCount(0); // 清空表格
            for (Transition t : firingRates.keySet()) {
                double rate = firingRates.getOrDefault(t, 0.0);
                firingmodel.addRow(new Object[]{t, rate});
            }

            // 刷新 capacity 表格
            DefaultTableModel captarModel = (DefaultTableModel) captarTable.getModel();
            captarModel.setRowCount(0);
            for (Place p : capacities.keySet()) {
                long cap = capacities.getOrDefault(p, 0L);
                long tar = targets.getOrDefault(p, 0L);
                captarModel.addRow(new Object[]{p, cap, tar});
            }

            rd.setFiringRates(firingRates);
            rd.setCapacities(capacities);
            rd.setTarget(targets);
    
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error importing XML: " + ex.getMessage(),
                    "Import Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_importButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        DefaultTableModel firingmodel = (DefaultTableModel) firingrateTable.getModel();
        DefaultTableModel captarModel = (DefaultTableModel) captarTable.getModel();
        for (int i = 0; i < firingmodel.getRowCount(); i++) {
            Transition t = (Transition) firingmodel.getValueAt(i, 0);
            double rate = Double.parseDouble(firingmodel.getValueAt(i, 1).toString());

            if (rate == 0.0) {
                int result = JOptionPane.showConfirmDialog(this,
                        "Firing rate is 0.0 for transition \"" + t.toString() + "\". Do you want to continue?",
                    "Zero Firing Rate",
                        JOptionPane.YES_NO_OPTION);
                if (result != JOptionPane.YES_OPTION) return;
            }

            firingRates.put(t, rate);
        }

        for (int i = 0; i < captarModel.getRowCount(); i++) {
            Place p = (Place) captarModel.getValueAt(i, 0);
            long capacity = Long.parseLong(captarModel.getValueAt(i, 1).toString());
            long target = Long.parseLong(captarModel.getValueAt(i, 2).toString());
            capacities.put(p, capacity);
            targets.put(p, target);
        }

        rd.setFiringRates(firingRates);
        rd.setCapacities(capacities);
        rd.setTarget(targets);
        this.dispose();

        // System.out.println("Saved Firing Rates:");
        // for (Map.Entry<Transition, Double> entry : firingRates.entrySet()) {
        //     System.out.println(entry.getKey().getProperty("name") + ": " + entry.getValue());
        // }

        
    
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel capacityLabel;
    private javax.swing.JTable captarTable;
    private javax.swing.JLabel firingrateLabel;
    private javax.swing.JTable firingrateTable;
    private javax.swing.JButton importButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
